server:
  port: 8081
spring:
  application:
    name: "msSolicitudes"
  devtools:
    add-properties: false
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.xml"
    url: "jdbc:postgresql://localhost:5432/solicitudes"
    user: "root"
    password: "postresql"
  profiles:
    include: null
adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8080"
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8081"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "solicitudes"
    username: "root"
    password: "postresql"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
